{
  try {
    return task.process();
  }
 catch (  Throwable t) {
    log.warn(t,"ResumableTask completed exceptionally");
    return ResumableTask.TaskStatus.finished();
  }
}
