{
  try {
    functionAssertions.assertFunction(expression,expected);
  }
 catch (  Throwable e) {
    throw new RuntimeException("Error processing " + expression,e);
  }
  return null;
}
