{
  try {
    runnable.run();
    throw new AssertionError("Method din't throw an exception as it was expected");
  }
 catch (  Exception expected) {
  }
}
